### ISSUE TITLE
ARM version?

### ISSUE THREAD

**Issue by MGoeppl** [forewing/webrcon-server#6]
Hi there,
is it possible to create an ARM version of the rcon server for the RasPi? This would be awesome!
Thanks!

**Comment by forewing** [comment]
Thank you for submitting the issue! 

Go is a cross-platform language so it can be easily done. Here are some options:

### Build directly on your raspberry pi

Install Go 1.16 on your rpi and follow the install guide in [README.md](./README.md)

### Or cross-build on your PC

Install Go 1.16 on your PC and follow the install guide as above, but before run `go build`, set environment variable `GOOS=linux`, `GOARCH=arm`, `GOARM=5` (You can check your rpi's arm version and change GOARM to 5/6/7)

**Comment by forewing** [comment]
I will add pre-build arm binary on CI/release pages later, and then you will be able to easily download them without building on your own.

The attached file is an armv6 version binary of webrcon-server, which you may use for now.

[webrcon-server_linux_armv6.tar.gz](https://github.com/forewing/webrcon-server/files/6108169/webrcon-server_linux_armv6.tar.gz)

**Comment by forewing** [comment]
I updated the build.sh to support cross-compile in d694eea, later releases will ship binaries of the following OS/Arch pair:

| GOOS | GOARCH | File |
| :-: | :-: | :- |
| darwin | amd64 | webrcon-server_darwin_amd64.tar.gz |
| darwin | arm64 | webrcon-server_darwin_arm64.tar.gz |
| linux | amd64 | webrcon-server_linux_amd64.tar.gz |
| linux | arm64 | webrcon-server_linux_arm64.tar.gz |
| linux | arm | webrcon-server_linux_arm.tar.gz |
| windows | amd64 |webrcon-server_windows_amd64.zip  |
